config/routes.rb
Rails.application.routes.draw do
  resources :devices

  # Redirects with constraints
  # Commented out in original; updated syntax for Rails 7
  # get "*path", to: redirect("https://www.sportfit.app/%{path}"), constraints: { protocol: "http://" }
  # get "*path", to: redirect("https://www.sportfit.app/%{path}"), constraints: { subdomain: "" }

  # Trackers
  match "/trackers/weightStats", to: "trackers#weightStats", via: [:get, :post] # Keeping match for multiple verbs
  resources :trackers

  # Eventos
  match "/events/getAll", to: "eventos#getActiveEvents", via: [:get, :post]
  resources :eventos

  resources :mcards
  resources :likes

  # Comentarios
  match "/comments/getAll", to: "comentarios#getAll", via: [:get, :post]
  resources :comentarios do # Evita generar rutas automáticas innecesarias
    member do
      delete :destroy # Ruta DELETE estándar
      post :destroy   # Permitir POST para simular DELETE
    end
  end

  # Nutritions
  match "/nutrition/appointments", to: "nutritions#getMyAppointments", via: [:get, :post]
  resources :nutritions

  resources :entrenamientos

  # Asistencia
  match "/asistencia/stats", to: "asistencia#estadistica", via: [:get, :post]
  match "/asistencia/lista", to: "asistencia#listaDeAsistencia", via: [:get, :post]
  match "/asistencia/startWod", to: "asistencia#startWod", via: [:get, :post]
  match "/asistencia/endWod", to: "asistencia#endWod", via: [:get, :post]
  match "/asistencia/activeWods", to: "asistencia#activeWod", via: [:get, :post]
  get '/asistencia/stats/montly', to: 'asistencia#monthly_chart'
  resources :asistencia

  resources :accesses
  resources :diccionarios
  resources :wod_schedules
  resources :wod_items

  # Wod_roots
  get "/wod_roots/mywods", to: "wod_roots#getMyWods"
  post "/wod_roots/getSingleWodItem", to: "wod_roots#getSingleWodItem"
  post "/wod_roots/getWodItems", to: "wod_roots#getWodItems"
  resources :wod_roots

  resources :ejercicios
  resources :box_schedules
  resources :tickets
  resources :corte_cajas

  # Dashboards
  get "/dashboards/salesInfo", to: "dashboards#salesInfo"
  get "/dashboards/salesInfo2", to: "dashboards#salesInfo2"
  get "/dashboards/salesInfo3", to: "dashboards#salesInfo3"
  post "/", to: "dashboards#dummy"
  resources :dashboards

  resources :paquetes
  resources :correos

  match "/contactme", to: "correos#contactus", via: [:get, :post]

  resources :notificaciones

  # Recompensa_obtenidas
  match "/rewards/myRewards", to: "recompensa_obtenidas#getMyRewards", via: [:get, :post]
  resources :recompensa_obtenidas

  resources :rewards
  # Entradas
  get "/entradas/salir", to: "entradas#logOut"
  post "/entradas/logWithCard", to: "entradas#logWithCard"
  get "/entradas/keypad/:uid", to: "entradas#showKeypad"
  get "/entradas/contactless/:uid", to: "entradas#showNFC"
  get "/entradas/biometric/:uid", to: "entradas#showBiometric"
  post "/entradas/logWithUser", to: "entradas#logWithUser" # Assuming GET; adjust if POST is intended
  match "/entradas/logWithKeyPad", to: "entradas#logWithKeypad", via: [:post, :options]
  resources :entradas

  resources :establecimientos
  resources :pagos
  resources :tipo_cuenta

  # Usuarios
  match "/coinLogin", to: "usuarios#coinlessLogin", via: [:get, :post]
  match "/coinRegister", to: "usuarios#coinlessRegister", via: [:get, :post]
  match "/setPrice", to: "usuarios#coinlessPrice", via: [:get, :post]
  match "/getPrice", to: "usuarios#getCoinlessPrice", via: [:get, :post]
  get "/usuarios/fakeUser", to: "usuarios#fakeUser"
  get "/usuarios/welcomeUser", to: "usuarios#welcomeUser"
  get "/usuarios/openDoor", to: "usuarios#openDoor"
  get "/usuarios/closeDoor", to: "usuarios#closeDoor"
  get "/usuarios/createToken", to: "usuarios#createToken"
  match "/usuarios/fromMobile", to: "usuarios#createMobile", via: [:post, :options]
  match "/usuarios/loginMobile", to: "usuarios#loginMobile", via: [:post, :options]
  match "/usuarios/downloadBeacons", to: "usuarios#downloadBeacons", via: [:post, :options]
  get "/usuarios/downloadPlacesFromNetwork", to: "usuarios#downloadPlacesFromNetwork"
  match "/usuarios/mostActive", to: "usuarios#mostActiveUsers", via: [:post, :get]
  get "/usuarios/stats", to: "usuarios#statsByUser"
  resources :usuarios do
    # Add this line inside the resources block if mylogin is a member action (specific to a user)
    # get 'mylogin', on: :member
    # Or as a collection action (not tied to a specific user)
    get 'login', on: :collection
  end

  post "/usuarios/buscar", to: "usuarios#buscarNombre"

  # Pagos (merged duplicate routes)
  get "/pagos/makePayment", to: "pagos#makePayment" # Original match
  post "/pagos/makePayment", to: "pagos#makePayment" # Explicit POST route
  post "/pagos/corteCaja", to: "pagos#corteCaja"
  get "/pagos/makeCardPayment", to: "pagos#makeCardPayment"
  get "/pagos/pauseUser", to: "pagos#pauseUser"
  get "/pagos/incomingFromGateway", to: "pagos#incomingFromGateway"

  # Removed legacy wildcard route comment
end

app/models/establecimiento.rb
class Establecimiento < ActiveRecord::Base
end

app/controllers/establecimientos_controller.rb
#encoding: utf-8
class EstablecimientosController < ApplicationController
  # GET /establecimientos
  # GET /establecimientos.json
  def index
    if session[:cuser]==nil
      redirect_to "/"
      return
    end
    # if session[:cuser].tipo!=1
    #   redirect_to "/"
    #   return
    # end
    withAccess=Access.where(:adduser=>1,:user_id=>session[:cuser].id).index_by(&:establecimiento_id).keys
    @establecimientos = Establecimiento.where(:networkid=>session[:cuser].networkid)
    if session[:cuser].tipo==isAdmin()
      @establecimientos=Establecimiento.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @establecimientos }
    end
  end

  # GET /establecimientos/1
  # GET /establecimientos/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @establecimiento }
    end
  end

  # GET /establecimientos/new
  # GET /establecimientos/new.json
  def new
    @establecimiento = Establecimiento.new
    @scheduleTable=Hash.new
    @scheduleTable["mon"]=[]
    @scheduleTable["tue"]=[]
    @scheduleTable["wed"]=[]
    @scheduleTable["thu"]=[]
    @scheduleTable["fri"]=[]
    @scheduleTable["sat"]=[]
    @scheduleTable["sun"]=[]
    puts @scheduleTable.inspect
    @selectedScheduleTable=[]
    @groupedBy=[]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @establecimiento }
    end
  end

  # GET /establecimientos/1/edit
  def edit
    @establecimiento = Establecimiento.find(params[:id])
    if session[:cuser].tipo == isAdmin()
      # @establecimiento = Establecimiento.find(params[:id])
    elsif session[:cuser].tipo == isManager() or session[:cuser].tipo == isReceptionist()
      @establecimiento = Establecimiento.where(:id=>params[:id], :networkid=>session[:cuser].networkid).last
    else
      redirect_to "/"
      return
    end
    @scheduleTable=Hash.new
    @scheduleTable["mon"]=BoxSchedule.where(:establecimiento_id=>params[:id],:weekday=>"mon").index_by(&:timetable).keys
    @scheduleTable["tue"]=BoxSchedule.where(:establecimiento_id=>params[:id],:weekday=>"tue").index_by(&:timetable).keys
    @scheduleTable["wed"]=BoxSchedule.where(:establecimiento_id=>params[:id],:weekday=>"wed").index_by(&:timetable).keys
    @scheduleTable["thu"]=BoxSchedule.where(:establecimiento_id=>params[:id],:weekday=>"thu").index_by(&:timetable).keys
    @scheduleTable["fri"]=BoxSchedule.where(:establecimiento_id=>params[:id],:weekday=>"fri").index_by(&:timetable).keys
    @scheduleTable["sat"]=BoxSchedule.where(:establecimiento_id=>params[:id],:weekday=>"sat").index_by(&:timetable).keys
    @scheduleTable["sun"]=BoxSchedule.where(:establecimiento_id=>params[:id],:weekday=>"sun").index_by(&:timetable).keys
    puts @scheduleTable.inspect
    @selectedScheduleTable=BoxSchedule.where(:establecimiento_id=>params[:id]).index_by(&:weekday).keys
    @groupedBy=[]
    cdays=["mon","tue","wed","thu","fri","sat","sun"]
    remainingdays=["mon","tue","wed","thu","fri","sat","sun"]
    currentg=0
    cdays.each do |sday|
      if @scheduleTable[sday].length>0 and remainingdays.index(sday)!=nil
        @groupedBy.push([sday])
        remainingdays.delete(sday)
        remainingdays.each do |remain|
          if ((@scheduleTable[sday] & @scheduleTable[remain]) == @scheduleTable[sday]) and @scheduleTable[sday].length==@scheduleTable[remain].length
            @groupedBy[@groupedBy.length-1].push(remain)
            remainingdays.delete(remain)
          end
        end
      end
    end
    puts "--grupo"
    puts @groupedBy.inspect
    puts "--grupo"
    @establecimiento = Establecimiento.find(params[:id])
  end

  # POST /establecimientos
  # POST /establecimientos.json
  def create
    unless [isAdmin, isManager, isReceptionist].include?(session[:cuser].tipo)
      redirect_to "/"
      return
    end
  
    # Handle file upload if present
    uploaded_filename = nil
    if params[:establecimiento][:foto].present?
      uploaded_filename = params[:establecimiento][:foto].original_filename
      path = Rails.root.join("public", "images", uploaded_filename)
      File.binwrite(path, params[:establecimiento][:foto].read)
    end
  
    @establecimiento = Establecimiento.new(establecimiento_params(uploaded_filename))
    uniqID = SecureRandom.hex
    @establecimiento.uniq = uniqID[0..3]
    @establecimiento.networkid = session[:cuser].networkid
  
    respond_to do |format|
      if @establecimiento.save
        @permissionLevel = Access.new
        @permissionLevel.user_id = session[:cuser].id
        @permissionLevel.establecimiento_id = @establecimiento.id
        @permissionLevel.level_access = 30
        @permissionLevel.save
  
        regenerateLocationSchedule(@establecimiento, params[:fulltimetable])
        format.html { redirect_to "/establecimientos", notice: 'Se creó un Establecimiento correctamente.' }
        format.json { render json: @establecimiento, status: :created, location: @establecimiento }
      else
        format.html { render action: "new", status: :unprocessable_entity }
        format.json { render json: @establecimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_old
    if session[:cuser].tipo == isAdmin() or session[:cuser].tipo == isManager() or session[:cuser].tipo == isReceptionist()
      
    else
      redirect_to "/"
      return
    end
    @establecimiento = Establecimiento.new(params[:establecimiento])
    if params[:establecimiento][:foto]!=nil
      puts params[:establecimiento][:foto].original_filename
      path = File.join(Rails.root + "public/images", params[:establecimiento][:foto].original_filename)
      # write the file
      File.open(path, "w+b") { |f| f.write(params[:establecimiento][:foto].read) }
      # limpiamos
      params[:establecimiento][:foto]=params[:establecimiento][:foto].original_filename
      @establecimiento.foto=params[:establecimiento][:foto]
    end
    uniqID=SecureRandom.hex
    @establecimiento.uniq=uniqID[0..3]
    @establecimiento.networkid=session[:cuser].networkid
    if params[:establecimiento][:openpayprueba] == 'on' or params[:establecimiento]['openpayprueba'] == 'on'
      @establecimiento.openpayprueba == 1      
    end
    respond_to do |format|
      if @establecimiento.save
        @permissionLevel=Access.new
        @permissionLevel.user_id=session[:cuser].id
        @permissionLevel.establecimiento_id=@establecimiento.id
        @permissionLevel.level_access=30
        @permissionLevel.save

        regenerateLocationSchedule(@establecimiento,params[:fulltimetable])
        format.html { redirect_to "/establecimientos", notice: 'Se creó un Establecimiento correctamente.' }
        format.json { render json: @establecimiento, status: :created, location: @establecimiento }
      else
        format.html { render action: "new" }
        format.json { render json: @establecimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /establecimientos/1
  # PUT /establecimientos/1.json
  def update
    @establecimiento = find_establecimiento
  
    # Redirect if no valid establecimiento is found (non-admin/manager/receptionist)
    return redirect_to "/" unless @establecimiento
  
    # Handle file upload if present
    if params[:establecimiento][:foto].present?
      filename = params[:establecimiento][:foto].original_filename
      path = Rails.root.join("public", "images", filename)
      File.binwrite(path, params[:establecimiento][:foto].read)
      # Set the filename in permitted params later
    end
  
    respond_to do |format|
      if @establecimiento.update(establecimiento_params(filename))
        regenerateLocationSchedule(@establecimiento, params[:fulltimetable])
        format.html { redirect_to "/establecimientos", notice: 'Establecimiento correctamente editado.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit", status: :unprocessable_entity }
        format.json { render json: @establecimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /establecimientos/1
  # DELETE /establecimientos/1.json
  def destroy
    @establecimiento = Establecimiento.find(params[:id])
    if session[:cuser].tipo == isAdmin()
      # @establecimiento = Establecimiento.find(params[:id])
    elsif session[:cuser].tipo == isManager() or session[:cuser].tipo == isReceptionist()
      @establecimiento = Establecimiento.where(:id=>params[:id], :networkid=>session[:cuser].networkid).last
    else
      redirect_to "/"
      return
    end
    @establecimiento.destroy

    respond_to do |format|
      format.html { redirect_to establecimientos_url }
      format.json { head :no_content }
    end
  end
  
  private
  
  def find_establecimiento
    case session[:cuser]&.tipo
    when isAdmin
      Establecimiento.find(params[:id])
    when isManager, isReceptionist
      Establecimiento.where(id: params[:id], networkid: session[:cuser].networkid).last
    else
      nil
    end
  end
  
  def establecimiento_params(uploaded_filename = nil)
    permitted = params.require(:establecimiento).permit(
      :beacon,:major,:minor,:nombre, :calle, :numero, :colonia, :servicios, :telefono, :email, 
      :descripcion, :coordenadas, :openpayprueba, :openpayid, :openpaypub, :openpaypri, :foto
    )
    # Convert openpayprueba to boolean
    permitted[:openpayprueba] = permitted[:openpayprueba] == "on"
    # Set foto to filename if uploaded
    permitted[:foto] = uploaded_filename if uploaded_filename
    permitted
  end
  
  def update_old

    @establecimiento = Establecimiento.find(params[:id])
    if session[:cuser].tipo == isAdmin()
      # @establecimiento = Establecimiento.find(params[:id])
    elsif session[:cuser].tipo == isManager() or session[:cuser].tipo == isReceptionist()
      @establecimiento = Establecimiento.where(:id=>params[:id], :networkid=>session[:cuser].networkid).last

app/helpers/establecimientos_helper.rb
module EstablecimientosHelper
end

app/views/establecimientos/_form.html.erb
<%= simple_form_for @establecimiento, :html => {:multipart => true} do |f|%>
  <div class="card">
    <div class="card-header border-0">
      <div class="row align-items-center">
        <div class="col">
          <h3 class="mb-0">Datos de establecimiento</h3>
          <% if @establecimiento.id != nil %>
            <span class="badge badge-pill badge-primary">(CLAVE para usuarios: <%= @establecimiento.uniq %> )</span>
          <% end %>
        </div>
        <div class="col text-right">
          <% if session[:cuser].tipo == 1 || session[:cuser].tipo == 2 || session[:cuser].tipo == 4 %>
            <button type="submit" class="btn btn-success">Guardar</button>
            <% if @establecimiento.id != nil %>
              <%= link_to 'Borrar', @establecimiento, method: :delete, data: { confirm: 'Se borrará el establecimiento actual, ¿Desea continuar?' }, :class => "btn btn-warning" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="card-body">
      <% if @establecimiento.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@establecimiento.errors.count, "error") %> prohibited this establecimiento from being saved:</h2>
          <ul>
            <% @establecimiento.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group last">
        <div class="fileinput fileinput-new" data-provides="fileinput">
          <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
            <% if @establecimiento.foto != nil && @establecimiento.foto != "" %>
              <img src="/images/<%= @establecimiento.foto %>" alt="Establecimiento" style="max-width: 350px; max-height: 200px;"/>
            <% else %>
              <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" alt=""/>
            <% end %>                       
          </div>
          <br>
          <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
          <div>
            <br> 
            <%= f.input :foto, :as => :file, label: 'Fotografía', input_html: { accept: 'image/*', 'data-show-preview' => false, 'data-max-file-size' => 1024, 'data-resize-if-size-more-than' => 1024, 'data-msg-no-files-selected' => 'Imagen excede el tamaño', 'data-msg-validation-error' => 'Archivo excede el tamaño', 'data-msg-placeholder' => 'Selecciona una imagen' } %>
          </div>
        </div>
      </div>
      
      <%= f.input :nombre, required: true, label: "Nombre", input_html: { class: 'col-md-12 form-control' } %>
      <%= f.input :calle, required: true, label: "Calle", input_html: { class: 'col-md-12 form-control' } %>
      <%= f.input :numero, required: true, label: "Número", input_html: { class: 'col-md-12 form-control' } %> 
      <%= f.input :colonia, required: true, label: "Colonia", input_html: { class: 'col-md-12 form-control' } %> 
      <%= f.input :servicios, required: true, label: "Servicios", input_html: { class: 'col-md-12 form-control' } %> 
      <%= f.input :telefono, required: true, label: "Teléfono", input_html: { class: 'col-md-12 form-control' } %>
      <%= f.input :email, :as => :email, required: true, label: "E-mail", input_html: { class: 'col-md-12 form-control' } %>
      <%= render "shared/scheduleComponent" %>
      <%= f.input :descripcion, required: true, label: "Descripción", input_html: { class: 'col-md-12 form-control' } %>
      
      <!-- Reemplazo del campo de coordenadas por un mapa -->
      <div class="form-group">
        <label>Ubicación</label>
        <div id="map" style="height: 400px; width: 100%;"></div>
        <%= f.hidden_field :coordenadas, id: 'coordenadas' %>
        <small class="form-text text-muted">Arrastra el marcador para seleccionar la ubicación del establecimiento.</small>
      </div>

      <% if session[:cuser].tipo == isAdmin() || session[:cuser].tipo == isManager() %>
        <div class="input boolean optional establecimiento_openpayprueba">
          <div class="custom-control custom-checkbox mb-3">
            <input class="custom-control-input" id="establecimiento_openpayprueba" name="establecimiento[openpayprueba]" type="checkbox" <% if @establecimiento.openpayprueba != nil && @establecimiento.openpayprueba != 0 %>checked checked="checked"<% end %>>
            <label class="custom-control-label" for="establecimiento_openpayprueba">
              Usar openpay en modo prueba (DESACTIVE para cobrar con tarjetas reales).
            </label>
          </div>
        </div>
      <% end %>
      <%= f.input :openpayid, label: "Openpay id", input_html: { class: 'col-md-12 form-control' } %> 
      <%= f.input :openpaypub, label: "Openpay public key", input_html: { class: 'col-md-12 form-control' } %> 
      <%= f.input :openpaypri, label: "Openpay private key", input_html: { class: 'col-md-12 form-control' } %> 
      <% if session[:cuser].tipo == 1 %>
        <%= f.input :beacon, required: false, label: "iBeacon UUID", input_html: { class: 'col-md-12 form-control' } %> 
        <%= f.input :major, required: false, label: "Major", input_html: { class: 'col-md-12 form-control' } %> 
        <%= f.input :minor, required: false, label: "Minor", input_html: { class: 'col-md-12 form-control' } %> 
      <% end %>
    </div>
    <div class="actions"></div>
  </div>

  <!-- Script para inicializar el mapa -->
  <script>
    function initEstMap() {
      // Coordenadas iniciales (por ejemplo, centro de México)
      let initialLatLng = { lat: 19.4326, lng: -99.1332 };
      
      // Si ya hay coordenadas guardadas, usarlas
      <% if @establecimiento.coordenadas.present? %>
        const coords = "<%= @establecimiento.coordenadas %>".split(",");
        initialLatLng = { lat: parseFloat(coords[0]), lng: parseFloat(coords[1]) };
      <% end %>

      // Inicializar el mapa
      const map = new google.maps.Map(document.getElementById("map"), {
        zoom: 15,
        center: initialLatLng,
      });

      // Marcador draggable
      const marker = new google.maps.Marker({
        position: initialLatLng,
        map: map,
        draggable: true,
      });

      // Actualizar el campo oculto cuando se mueve el marcador
      google.maps.event.addListener(marker, 'dragend', function() {
        const position = marker.getPosition();
        document.getElementById('coordenadas').value = `${position.lat()},${position.lng()}`;
      });

      // También actualizar al hacer clic en el mapa
      map.addListener('click', function(e) {
        marker.setPosition(e.latLng);
        document.getElementById('coordenadas').value = `${e.latLng.lat()},${e.latLng.lng()}`;
      });
    }

    // Cargar el mapa cuando la página esté lista
    document.addEventListener('DOMContentLoaded', function() {
      initEstMap();
    });
  </script>
<% end %>

app/views/establecimientos/edit.html.erb
<%= render 'form' %>


<%= link_to 'Back', establecimientos_path %>
<br>
<br>
<br>
<br>

app/views/establecimientos/index.html.erb
<div class="row">
  <div class="col-xl-12 mb-5 mb-xl-0">
    <div class="card shadow">
      <div class="card-header border-0">
        <div class="row align-items-center">
          <div class="col">
            <h3 class="mb-0">Lista de establecimientos</h3>
          </div>
          <div class="col text-right">
            <% if Access.where(:user_id=>session[:cuser].id,:addestablecimiento=>1).length>0 or session[:cuser].tipo==1 or session[:cuser].tipo==2%>
                <a href="/establecimientos/new" class="btn btn-sm btn-primary">Nuevo establecimiento</a>
            <% end %>
          </div>
        </div>
      </div>
      <div class="table-responsive">
        <!-- Projects table -->
        <table class="table align-items-center table-flush">
          <thead class="thead-light">
            <tr>
              <th scope="col">
                    Nombre
                </th>
                <th scope="col">
                        Calle / Numero
                </th>
                <th scope="col">
                    Colonia
                </th>
                <th scope="col">
                        Servicios
                </th>
                <th scope="col">
                        Horario
                </th>
                <th scope="col">
                        
                </th>
            </tr>
          </thead>
          <tbody>
            <% @establecimientos.each do |establecimiento| %>
            <tr>
                <th scope="row">
                    <div class="media align-items-center">
                        <a href="#" class="avatar rounded-circle mr-3">
                            <img alt="Image placeholder" src="/images/<%= establecimiento.foto %>">
                        </a>
                        <div class="media-body">
                            <span class="mb-0 text-sm"><a href="/establecimientos/<%= establecimiento.id %>/edit" class="primary-link"><%= establecimiento.nombre %></a></span>
                        </div>
                    </div>
                </th>
                <td>
                        <%= establecimiento.calle %> <%= establecimiento.numero %>
                </td>
                <td>
                        <%= establecimiento.colonia %>
                </td>
                <td>
                        <%= establecimiento.servicios %>
                </td>
                <td>
                    <span class="bold theme-font"><%= establecimiento.horario %></span>
                </td>
                <td class="text-right">
                    <div class="dropdown">
                      <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <i class="fas fa-ellipsis-v"></i>
                      </a>
                      <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                          <%= link_to 'Editar', edit_establecimiento_path(establecimiento), { :class=>"dropdown-item" } %>
                      </div>
                    </div>
                </td>
            </tr>
            <% end %>    
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/establecimientos/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', establecimientos_path %>

app/views/establecimientos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @establecimiento.id %>
</p>

<p>
  <b>Nombre:</b>
  <%= @establecimiento.nombre %>
</p>

<p>
  <b>Calle:</b>
  <%= @establecimiento.calle %>
</p>

<p>
  <b>Numero:</b>
  <%= @establecimiento.numero %>
</p>

<p>
  <b>Colonia:</b>
  <%= @establecimiento.colonia %>
</p>

<p>
  <b>Servicios:</b>
  <%= @establecimiento.servicios %>
</p>

<p>
  <b>Horario:</b>
  <%= @establecimiento.horario %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @establecimiento.descripcion %>
</p>


<%= link_to 'Edit', edit_establecimiento_path(@establecimiento) %> |
<%= link_to 'Back', establecimientos_path %>