config/routes.rb
Rails.application.routes.draw do
  resources :devices

  # Redirects with constraints
  # Commented out in original; updated syntax for Rails 7
  # get "*path", to: redirect("https://www.sportfit.app/%{path}"), constraints: { protocol: "http://" }
  # get "*path", to: redirect("https://www.sportfit.app/%{path}"), constraints: { subdomain: "" }

  # Trackers
  match "/trackers/weightStats", to: "trackers#weightStats", via: [:get, :post] # Keeping match for multiple verbs
  resources :trackers

  # Eventos
  match "/events/getAll", to: "eventos#getActiveEvents", via: [:get, :post]
  resources :eventos

  resources :mcards
  resources :likes

  # Comentarios
  match "/comments/getAll", to: "comentarios#getAll", via: [:get, :post]
  resources :comentarios do # Evita generar rutas automáticas innecesarias
    member do
      delete :destroy # Ruta DELETE estándar
      post :destroy   # Permitir POST para simular DELETE
    end
  end

  # Nutritions
  match "/nutrition/appointments", to: "nutritions#getMyAppointments", via: [:get, :post]
  resources :nutritions

  resources :entrenamientos

  # Asistencia
  match "/asistencia/stats", to: "asistencia#estadistica", via: [:get, :post]
  match "/asistencia/lista", to: "asistencia#listaDeAsistencia", via: [:get, :post]
  match "/asistencia/startWod", to: "asistencia#startWod", via: [:get, :post]
  match "/asistencia/endWod", to: "asistencia#endWod", via: [:get, :post]
  match "/asistencia/activeWods", to: "asistencia#activeWod", via: [:get, :post]
  get '/asistencia/stats/montly', to: 'asistencia#monthly_chart'
  resources :asistencia

  resources :accesses
  resources :diccionarios
  resources :wod_schedules
  resources :wod_items

  # Wod_roots
  get "/wod_roots/mywods", to: "wod_roots#getMyWods"
  post "/wod_roots/getSingleWodItem", to: "wod_roots#getSingleWodItem"
  post "/wod_roots/getWodItems", to: "wod_roots#getWodItems"
  resources :wod_roots

  resources :ejercicios
  resources :box_schedules
  resources :tickets
  resources :corte_cajas

  # Dashboards
  get "/dashboards/salesInfo", to: "dashboards#salesInfo"
  get "/dashboards/salesInfo2", to: "dashboards#salesInfo2"
  get "/dashboards/salesInfo3", to: "dashboards#salesInfo3"
  post "/", to: "dashboards#dummy"
  resources :dashboards

  resources :paquetes
  resources :correos

  match "/contactme", to: "correos#contactus", via: [:get, :post]

  resources :notificaciones

  # Recompensa_obtenidas
  match "/rewards/myRewards", to: "recompensa_obtenidas#getMyRewards", via: [:get, :post]
  resources :recompensa_obtenidas

  resources :rewards
  # Entradas
  get "/entradas/salir", to: "entradas#logOut"
  post "/entradas/logWithCard", to: "entradas#logWithCard"
  get "/entradas/keypad/:uid", to: "entradas#showKeypad"
  get "/entradas/contactless/:uid", to: "entradas#showNFC"
  get "/entradas/biometric/:uid", to: "entradas#showBiometric"
  post "/entradas/logWithUser", to: "entradas#logWithUser" # Assuming GET; adjust if POST is intended
  match "/entradas/logWithKeyPad", to: "entradas#logWithKeypad", via: [:post, :options]
  resources :entradas

  resources :establecimientos
  resources :pagos
  resources :tipo_cuenta

  # Usuarios
  match "/coinLogin", to: "usuarios#coinlessLogin", via: [:get, :post]
  match "/coinRegister", to: "usuarios#coinlessRegister", via: [:get, :post]
  match "/setPrice", to: "usuarios#coinlessPrice", via: [:get, :post]
  match "/getPrice", to: "usuarios#getCoinlessPrice", via: [:get, :post]
  get "/usuarios/fakeUser", to: "usuarios#fakeUser"
  get "/usuarios/welcomeUser", to: "usuarios#welcomeUser"
  get "/usuarios/openDoor", to: "usuarios#openDoor"
  get "/usuarios/closeDoor", to: "usuarios#closeDoor"
  get "/usuarios/createToken", to: "usuarios#createToken"
  match "/usuarios/fromMobile", to: "usuarios#createMobile", via: [:post, :options]
  match "/usuarios/loginMobile", to: "usuarios#loginMobile", via: [:post, :options]
  match "/usuarios/downloadBeacons", to: "usuarios#downloadBeacons", via: [:post, :options]
  get "/usuarios/downloadPlacesFromNetwork", to: "usuarios#downloadPlacesFromNetwork"
  match "/usuarios/mostActive", to: "usuarios#mostActiveUsers", via: [:post, :get]
  get "/usuarios/stats", to: "usuarios#statsByUser"
  resources :usuarios do
    # Add this line inside the resources block if mylogin is a member action (specific to a user)
    # get 'mylogin', on: :member
    # Or as a collection action (not tied to a specific user)
    get 'login', on: :collection
  end

  post "/usuarios/buscar", to: "usuarios#buscarNombre"

  # Pagos (merged duplicate routes)
  get "/pagos/makePayment", to: "pagos#makePayment" # Original match
  post "/pagos/makePayment", to: "pagos#makePayment" # Explicit POST route
  post "/pagos/corteCaja", to: "pagos#corteCaja"
  get "/pagos/makeCardPayment", to: "pagos#makeCardPayment"
  get "/pagos/pauseUser", to: "pagos#pauseUser"
  get "/pagos/incomingFromGateway", to: "pagos#incomingFromGateway"

  # Removed legacy wildcard route comment
end

app/models/reward.rb
class Reward < ActiveRecord::Base
end

app/controllers/rewards_controller.rb
# encoding: utf-8
class RewardsController < ApplicationController
  # GET /rewards
  # GET /rewards.json
  def index
    if session[:cuser].nil?
      redirect_to "/"
      return
    end
    unless [1, 2, 6].include?(session[:cuser].tipo)
      redirect_to "/"
      return
    end

    if session[:cuser].tipo != 1
      @rewards = Reward.where(networkid: session[:cuser].networkid)
      @won_rewards = RecompensaObtenida.where(networkid: session[:cuser].networkid)
    else 
      @rewards = Reward.all
      @won_rewards = RecompensaObtenida.all
    end

    # Filtros para historial de recompensas
    if params[:search].present?
      search = params[:search]
      nombre = search[:nombre].present? ? search[:nombre] : nil
      apellido = search[:apellido].present? ? search[:apellido] : nil
      recompensa = search[:recompensa].present? ? search[:recompensa] : nil

      # Filtrar usuarios por nombre y/o apellido
      if nombre || apellido
        usuarios = Usuario.where("nombre LIKE :nombre", nombre: "%#{nombre}%")
        usuarios = usuarios.where("apellido LIKE :apellido", apellido: "%#{apellido}%") if apellido
        @won_rewards = @won_rewards.where(usuarios_id: usuarios.pluck(:id))
      end

      # Filtrar por nombre de recompensa
      if recompensa
        rewards = Reward.where("titulo LIKE ?", "%#{recompensa}%")
        @won_rewards = @won_rewards.where(rewards_id: rewards.pluck(:id))
      end
    end

    # Paginación con 30 ítems por página
    @won_rewards = @won_rewards.order(created_at: :desc).paginate(page: params[:page], per_page: 30)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rewards }
    end
  end


  # GET /rewards/1
  # GET /rewards/1.json
  def show
    @reward = Reward.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reward }
    end
  end

  # GET /rewards/new
  # GET /rewards/new.json
  def new
    @reward = Reward.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reward }
    end
  end

  # GET /rewards/1/edit
  def edit
    @reward = Reward.find(params[:id])
  end

  # POST /rewards
  # POST /rewards.json
  def create
    @reward = Reward.new(reward_params)
    @reward.networkid=session[:cuser].networkid
    respond_to do |format|
      if @reward.save
        format.html { redirect_to "/rewards", notice: 'Se creó correctamente una recompensa.' }
        format.json { render json: @reward, status: :created, location: @reward }
      else
        format.html { render action: "new" }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rewards/1
  # PUT /rewards/1.json
  def update
    @reward = Reward.find(params[:id])

    respond_to do |format|
      if @reward.update(reward_params)
        format.html { redirect_to "/rewards", notice: 'La recompensa se actualizo correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  def reward_params
    params.require(:reward).permit(:titulo, :descripcion, :asistencia, :numpagos)
  end

  # DELETE /rewards/1
  # DELETE /rewards/1.json
  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy

    respond_to do |format|
      format.html { redirect_to rewards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= simple_form_for(@reward) do |f| %>
  <div class="card shadow">
    <div class="card-header border-0">
        <div class="row align-items-center">
          <div class="col">
            <h6 class="text-uppercase text-muted ls-1 mb-1">Se va a enviar un email al usuario cuando haya obtenido una recompensa.</h6>
            <h3 class="mb-0">Crear recompensa</h3>
          </div>
          <div class="col text-right">

            <button type="submit" class="btn btn-sm btn-primary">Guardar</button>
                            
          </div>
        </div>
    </div>
    <div class="card-body">
      <% if @reward.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

          <ul>
          <% @reward.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.input :titulo, required:true,label:"Nombre",input_html: { class:'col-md-12 form-control' } %>
      <%= f.input :descripcion, required:true,label:"Descripción",input_html: { class:'col-md-12 form-control' } %>
      <%= f.input :asistencia, required:true,label:"Asistencia requerida (días continuos de asistencia)",input_html: { class:'col-md-12 form-control' } %>
      <%= f.input :numpagos, required:true,label:"Número de pagos requeridos (total de pagos realizados para obtener recompensa)",input_html: { class:'col-md-12 form-control' } %>

    </div>
  </div>
<% end %>

app/views/rewards/edit.html.erb
<%= render 'form' %>

app/views/rewards/index.html.erb
<div class="row mt-5">
    <div class="col-xl-12 mb-5 mb-xl-0">
    <div class="card shadow">
        <div class="card-header border-0">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="mb-0">Registro de Recompensas</h3>
                </div>
                <div class="col text-right">
                    <a href="/rewards/new" class="btn btn-sm btn-primary">Nueva recompensa</a>
                </div>
            </div>
        </div>

        <div class="table-responsive">
            <table class="table align-items-center table-flush">
                <thead class="thead-light">
                    <tr class="uppercase">
                        <th scope="col">Nombre de recompensa</th>
                        <th scope="col">Descripción</th>
                        <th scope="col">Asistencias requeridas</th>
                        <th scope="col">Pagos requeridos</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <% @rewards.each do |reward| %>
                        <tr>
                            <th>
                                <a href="/rewards/<%= reward.id %>/edit" class="primary-link"><%= reward.titulo %></a>
                            </th>
                            <td><%= reward.descripcion %></td>
                            <td><%= reward.asistencia %></td>
                            <td><%= reward.numpagos %></td>
                            <td><%= link_to 'Borrar', reward, method: :delete, data: { confirm: 'Vas a eliminar esta recompensa, ¿Deseas continuar?' } %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-xl-12 mb-5 mb-xl-0">
            <div class="card shadow">
            <div class="card-header border-0">
                <div class="row align-items-center">
                    <div class="col">
                        <h3 class="mb-0">Historial de recompensas</h3>
                    </div>
                    <div class="col text-right">
                        <!-- <a href="#!" class="btn btn-sm btn-primary">See all</a> -->
                    </div>
                </div>
                <!-- Filter Form -->
                <div class="row mt-3 align-items-end">
                    <div class="col">
                        <%= form_with url: rewards_path, method: :get, local: true, class: "row g-2" do %>
                            <div class="col-md-3">
                                <%= label_tag :nombre, "Nombre", class: "form-label mb-1" %>
                                <%= text_field_tag "search[nombre]", params.dig(:search, :nombre), class: "form-control form-control-sm" %>
                            </div>
                            <div class="col-md-3">
                                <%= label_tag :apellido, "Apellido", class: "form-label mb-1" %>
                                <%= text_field_tag "search[apellido]", params.dig(:search, :apellido), class: "form-control form-control-sm" %>
                            </div>
                            <div class="col-md-3">
                                <%= label_tag :recompensa, "Recompensa", class: "form-label mb-1" %>
                                <%= text_field_tag "search[recompensa]", params.dig(:search, :recompensa), class: "form-control form-control-sm" %>
                            </div>
                            <div class="col-md-3 d-flex align-items-end">
                                <%= submit_tag "Buscar", class: "btn btn-primary btn-sm me-2" %>
                                <%= link_to "Limpiar", rewards_path, class: "btn btn-secondary btn-sm" %>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table align-items-center table-flush">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">Nombre / Apellido</th>
                            <th scope="col">Número de socio</th>
                            <th scope="col">Recompensa</th>
                            <th scope="col">Fecha</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% if @won_rewards.empty? %>
                            <tr>
                                <td colspan="4" class="text-center">No hay recompensas aún ganadas</td>
                            </tr>
                        <% else %>
                            <% @won_rewards.each do |reward| %>
                                <tr>
                                    <td><%= Usuario.find_by_id(reward.usuarios_id).nombre %> <%= Usuario.find_by_id(reward.usuarios_id).apellido %></td>
                                    <td><%= Usuario.find_by_id(reward.usuarios_id).numsocio %></td>
                                    <td><%= Reward.find_by_id(reward.rewards_id).titulo %></td>
                                    <td><%= reward.created_at.strftime('%d/%m/%Y') %></td>
                                </tr>
                            <% end %>
                        <% end %>
                    </tbody>
                </table>
            </div>
            <div class="card-footer py-4">
                <nav aria-label="...">
                    <%= will_paginate @won_rewards, page_links: true, inner_window: 1, outer_window: 1 %>
                </nav>
            </div>
            </div>
        </div>
    </div>
</div>
<br><br><br><br><br>

app/views/rewards/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', rewards_path %>

app/views/rewards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @reward.id %>
</p>

<p>
  <b>Asistencia:</b>
  <%= @reward.asistencia %>
</p>

<p>
  <b>Numpagos:</b>
  <%= @reward.numpagos %>
</p>

<p>
  <b>Peso:</b>
  <%= @reward.peso %>
</p>


<%= link_to 'Edit', edit_reward_path(@reward) %> |
<%= link_to 'Back', rewards_path %>