config/routes.rb
Rails.application.routes.draw do
  resources :devices

  # Redirects with constraints
  # Commented out in original; updated syntax for Rails 7
  # get "*path", to: redirect("https://www.sportfit.app/%{path}"), constraints: { protocol: "http://" }
  # get "*path", to: redirect("https://www.sportfit.app/%{path}"), constraints: { subdomain: "" }

  # Trackers
  match "/trackers/weightStats", to: "trackers#weightStats", via: [:get, :post] # Keeping match for multiple verbs
  resources :trackers

  # Eventos
  match "/events/getAll", to: "eventos#getActiveEvents", via: [:get, :post]
  resources :eventos

  resources :mcards
  resources :likes

  # Comentarios
  match "/comments/getAll", to: "comentarios#getAll", via: [:get, :post]
  resources :comentarios do # Evita generar rutas automáticas innecesarias
    member do
      delete :destroy # Ruta DELETE estándar
      post :destroy   # Permitir POST para simular DELETE
    end
  end

  # Nutritions
  match "/nutrition/appointments", to: "nutritions#getMyAppointments", via: [:get, :post]
  resources :nutritions

  resources :entrenamientos

  # Asistencia
  match "/asistencia/stats", to: "asistencia#estadistica", via: [:get, :post]
  match "/asistencia/lista", to: "asistencia#listaDeAsistencia", via: [:get, :post]
  match "/asistencia/startWod", to: "asistencia#startWod", via: [:get, :post]
  match "/asistencia/endWod", to: "asistencia#endWod", via: [:get, :post]
  match "/asistencia/activeWods", to: "asistencia#activeWod", via: [:get, :post]
  get '/asistencia/stats/montly', to: 'asistencia#monthly_chart'
  resources :asistencia

  resources :accesses
  resources :diccionarios
  resources :wod_schedules
  resources :wod_items

  # Wod_roots
  get "/wod_roots/mywods", to: "wod_roots#getMyWods"
  post "/wod_roots/getSingleWodItem", to: "wod_roots#getSingleWodItem"
  post "/wod_roots/getWodItems", to: "wod_roots#getWodItems"
  resources :wod_roots

  resources :ejercicios
  resources :box_schedules
  resources :tickets
  resources :corte_cajas

  # Dashboards
  get "/dashboards/salesInfo", to: "dashboards#salesInfo"
  get "/dashboards/salesInfo2", to: "dashboards#salesInfo2"
  get "/dashboards/salesInfo3", to: "dashboards#salesInfo3"
  post "/", to: "dashboards#dummy"
  resources :dashboards

  resources :paquetes
  resources :correos

  match "/contactme", to: "correos#contactus", via: [:get, :post]

  resources :notificaciones

  # Recompensa_obtenidas
  match "/rewards/myRewards", to: "recompensa_obtenidas#getMyRewards", via: [:get, :post]
  resources :recompensa_obtenidas

  resources :rewards
  # Entradas
  get "/entradas/salir", to: "entradas#logOut"
  post "/entradas/logWithCard", to: "entradas#logWithCard"
  get "/entradas/keypad/:uid", to: "entradas#showKeypad"
  get "/entradas/contactless/:uid", to: "entradas#showNFC"
  get "/entradas/biometric/:uid", to: "entradas#showBiometric"
  post "/entradas/logWithUser", to: "entradas#logWithUser" # Assuming GET; adjust if POST is intended
  match "/entradas/logWithKeyPad", to: "entradas#logWithKeypad", via: [:post, :options]
  resources :entradas

  resources :establecimientos
  resources :pagos
  resources :tipo_cuenta

  # Usuarios
  match "/coinLogin", to: "usuarios#coinlessLogin", via: [:get, :post]
  match "/coinRegister", to: "usuarios#coinlessRegister", via: [:get, :post]
  match "/setPrice", to: "usuarios#coinlessPrice", via: [:get, :post]
  match "/getPrice", to: "usuarios#getCoinlessPrice", via: [:get, :post]
  get "/usuarios/fakeUser", to: "usuarios#fakeUser"
  get "/usuarios/welcomeUser", to: "usuarios#welcomeUser"
  get "/usuarios/openDoor", to: "usuarios#openDoor"
  get "/usuarios/closeDoor", to: "usuarios#closeDoor"
  get "/usuarios/createToken", to: "usuarios#createToken"
  match "/usuarios/fromMobile", to: "usuarios#createMobile", via: [:post, :options]
  match "/usuarios/loginMobile", to: "usuarios#loginMobile", via: [:post, :options]
  match "/usuarios/downloadBeacons", to: "usuarios#downloadBeacons", via: [:post, :options]
  get "/usuarios/downloadPlacesFromNetwork", to: "usuarios#downloadPlacesFromNetwork"
  match "/usuarios/mostActive", to: "usuarios#mostActiveUsers", via: [:post, :get]
  get "/usuarios/stats", to: "usuarios#statsByUser"
  resources :usuarios do
    # Add this line inside the resources block if mylogin is a member action (specific to a user)
    # get 'mylogin', on: :member
    # Or as a collection action (not tied to a specific user)
    get 'login', on: :collection
  end

  post "/usuarios/buscar", to: "usuarios#buscarNombre"

  # Pagos (merged duplicate routes)
  get "/pagos/makePayment", to: "pagos#makePayment" # Original match
  post "/pagos/makePayment", to: "pagos#makePayment" # Explicit POST route
  post "/pagos/corteCaja", to: "pagos#corteCaja"
  get "/pagos/makeCardPayment", to: "pagos#makeCardPayment"
  get "/pagos/pauseUser", to: "pagos#pauseUser"
  get "/pagos/incomingFromGateway", to: "pagos#incomingFromGateway"

  # Removed legacy wildcard route comment
end

app/models/entrada.rb
class Entrada < ActiveRecord::Base
end

app/controllers/entradas_controller.rb
require 'pusher'
require 'thread'

class EntradasController < ApplicationController
  # CSRF protection with exception for logWithCard
  protect_from_forgery with: :exception, except: [:logWithCard]

  # Removed enable_sync (see notes below)

  before_action :setup_pusher, only: [:logWithCard, :logWithKeypad]

  private

  def setup_pusher
    Pusher.app_id = ENV['PUSHER_APP_ID'] || '95011'
    Pusher.key = ENV['PUSHER_KEY'] || '038727943ef67c486a35'
    Pusher.secret = ENV['PUSHER_SECRET'] || 'ef4fbb7ecffe7b7f8fed'
    Pusher.cluster = 'mt1'
    Pusher.logger = Rails.logger
    Pusher.encrypted = true
  end

  public

  def logWithUser
    entrando=Usuario.where(:email=>params[:username],:password=>params[:password])
    if entrando.length==1

      session[:cuser]=entrando.last
      if session[:cuser].tipo==1
        redirect_to "/dashboards"  
      else 
        redirect_to "/pagos"
      end
      
      return
    else
      redirect_to "/"
    end
  end

  def showKeypad
    @establecimiento_id=params[:uid]
    @isshow = false
    render :keypadlogin
  end

  def showNFC
    @isshow = false
    render :nfclogin
  end

  def showBiometric
    @isshow = false
    render :biometriclogin
  end

  def logOut
    session[:cuser]=nil
    redirect_to "/"
    return
  end

  def logWithCard
    usuario, establecimiento = find_user_and_establecimiento
    channel_hash = determine_channel_hash

    if usuario
      entrada = Entrada.create!(establecimientos_id: establecimiento, usuarios_id: usuario.id)

      if usuario.isaservice == 1 && (usuario.finalfecha.nil? || usuario.finalfecha >= DateTime.now)
        update_dashboard_signal(usuario)
        trigger_pusher(channel_hash, usuario, 'OK')
        return render json: 'OK'
      end

      handle_rewards_and_payment(usuario)
      pago_activo = Pago.where(usuarios_id: usuario.id).where('vence >= ?', Time.now).exists?
      if pago_activo || (usuario.finalfecha.present? && usuario.finalfecha >= DateTime.now)
        trigger_suitch_network if params[:device].present?
        trigger_pusher(channel_hash, usuario, 'OK')
        return render json: 'OK'
      else
        trigger_pusher(channel_hash, usuario, 'FAIL')
        return render json: 'NOT'
      end
    end

    trigger_pusher_not_found(channel_hash)
    render json: 'NOT'
  end

  def logWithKeypad
    usuario = if session[:cuser].tipo == isAdmin
      Usuario.find_by(numsocio: params[:usuario].to_i)
    else
      Usuario.find_by(networkid: session[:cuser].networkid, numsocio: params[:usuario].to_i)
    end
    handle_rewards_and_payment(usuario)
    respuesta = default_response
    if usuario
      respuesta = build_keypad_response(usuario)
      trigger_suitch_network_keypad if respuesta['log_errors'].empty? && respuesta['type'] != 'error'
    end

    respond_to do |format|
      format.json { render json: respuesta }
    end
  end

  def logWithBeacon
    # Placeholder for future implementation
  end

  # Standard CRUD actions
  def index
    return redirect_to root_path unless session[:cuser]
    @entradas = []
    @isshow = false
    respond_to do |format|
      format.html
      format.json { render json: @entradas }
    end
  end

  def show
    @entrada = Entrada.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @entrada }
    end
  end

  def new
    @entrada = Entrada.new
    respond_to do |format|
      format.html
      format.json { render json: @entrada }
    end
  end

  def edit
    @entrada = Entrada.find(params[:id])
  end

  def create
    @entrada = Entrada.new(entrada_params)
    respond_to do |format|
      if @entrada.save
        format.html { redirect_to @entrada, notice: 'Entrada was successfully created.' }
        format.json { render json: @entrada, status: :created, location: @entrada }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @entrada = Entrada.find(params[:id])
    respond_to do |format|
      if @entrada.update(entrada_params)
        format.html { redirect_to @entrada, notice: 'Entrada was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @entrada = Entrada.find(params[:id])
    @entrada.destroy
    respond_to do |format|
      format.html { redirect_to entradas_url, notice: 'Entrada was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def entrada_params
    params.require(:entrada).permit(:establecimientos_id, :usuarios_id, :networkid, :paquete) # Adjust as needed
  end

  def find_user_and_establecimiento
    if params[:device].present?
      device_type = params[:device]['type']
      if device_type == 'nfc'
        [Usuario.find_by(nfc: params[:device]['result']), params[:place]]
      elsif device_type == 'bio'
        biometric_value = "#{params[:device]['productId']}#{params[:device]['result']}"
        [Usuario.find_by(biometric: biometric_value), params[:place]]
      end
    else
      [Usuario.find_by(id: params[:userin]), Establecimiento.find_by(major: params[:major])&.id]
    end
  end

  def determine_channel_hash
    return 'njksdfwe23' unless session[:cuser]
    session[:cuser].gymorigin.present? ? Establecimiento.find_by(id: session[:cuser].gymorigin)&.uniq : session[:cuser].networkid
  end

  def update_dashboard_signal(usuario)
    update_signal = Dashboard.find_by(id: 1)
    update_signal&.update!(user_in: usuario.id)
  end

  def handle_rewards_and_payment(usuario)
    Rails.logger.info "Handling rewards and payment for user: #{usuario.id}"
    asistencias = Entrada.where(usuarios_id: usuario.id).count
    pagos_count = Pago.where(usuarios_id: usuario.id).count
    recompensas = Reward.where(asistencia: asistencias,networkid: usuario.networkid)

    recompensas.each do |single_reward|
      next if RecompensaObtenida.exists?(rewards_id: single_reward.id) and single_reward.numpagos < pagos_count
      Rails.logger.info "Found a matching reward: #{single_reward.titulo}"
      # verify if the payments are enough to get the reward
      RecompensaObtenida.create!(
        usuarios_id: usuario.id,
        rewards_id: single_reward.id,
        networkid: usuario.networkid
      )
      send_mail_to_user(usuario, single_reward)
    end

    update_dashboard_signal(usuario)
  end

  def send_mail_to_user(usuario, reward)
    sendMailToAddress(
      [{ 'email' => usuario.email, 'name' => "#{usuario.nombre} #{usuario.apellido}", 'type' => 'to' }],
      reward.descripcion,
      reward.titulo)
  end

  def trigger_pusher(channel_hash, usuario, status)
    Pusher.trigger(channel_hash, 'issue-subscription', {
      message: '',
      avatar: "/images/#{usuario.foto}",
      name: usuario.nombre,
      lastname: usuario.apellido,
      status: status
    })
  end

  def trigger_pusher_not_found(channel_hash)
    Pusher.trigger(channel_hash, 'issue-subscription', {
      message: 'No se encontró identificador',
      avatar: 'https://placehold.co/200x150/EFEFEF/AAAAAA?text=No+registrado',
      name: 'No registrado',
      lastname: '',
      status: 'NOT'
    })
  end

  def trigger_suitch_network
    origin_devices = Device.where(uid: params[:device]['deviceId'], networkid: session[:cuser].networkid)
    origin_devices.each do |single_device|
      next unless single_device.post_action
      suitch = Device.find_by(id: single_device.post_action)
      next unless suitch
      Rails.logger.info "Suitch UID: #{suitch.uid}"
      Thread.new do
        toggle_suitch(suitch, 'on')
        sleep 6
        toggle_suitch(suitch, 'off')
      end
    end
  end

  def toggle_suitch(suitch, state)
    url = "https://www.suitch.network/devices/send?token=#{suitch.uid}&secret_token=#{suitch.secret}&content=#{state}"
    uri = URI(url)
    Net::HTTP.get(uri)
  end

  def default_response
    {
      'nombre' => 'No se encontró usuario.',
      'plan' => 0,
      'planDesc' => 'Plan: Sin plan actualmente',
      'deuda' => 'Sin deuda este mes',
      'inscripcion' => 'NOT_PAID',
      'type' => 'error',
      'log_errors' => [],
      'photo' => ''
    }
  end

  def build_keypad_response(usuario)
    respuesta = {
      'type' => 'OK',
      'photo' => usuario.foto,
      'nombre' => "#{usuario.nombre} #{usuario.apellido}",
      'plan' => usuario.paquete,
      'planDesc' => usuario.paquete.present? ? "Plan: #{Paquete.find_by(id: usuario.paquete)&.nombre}" : 'Plan: Sin plan',
      'deuda' => 'Sin deuda este mes',
      'inscripcion' => 'NOT_PAID',
      'log_errors' => []
    }
    forma_de_pago = getPaymentDetails(usuario)
    respuesta['opid'] = forma_de_pago&.openpayid
    respuesta['oppub'] = forma_de_pago&.openpaypub
    establecimiento = Establecimiento.find_by(uniq: params[:uid])
    if establecimiento == nil
      establecimiento = -1
    else
      establecimiento = establecimiento.id
    end
    entrada = Entrada.new(
          usuarios_id: usuario.id,
          networkid: usuario.networkid,
          paquete: usuario.paquete,
          establecimientos_id: establecimiento,
          status:'success'
        )
    if usuario.paquete.present?
      paquete = Paquete.find_by(id: usuario.paquete)
      if paquete
        fecha_base = DateTime.new(Time.now.year, Time.now.month, 1)
        pagos_corriendo = Pago.where('vence > ?', fecha_base).where(usuarios_id: usuario.id).sum(:cantidad_original)
        deuda = paquete.precio.to_f - pagos_corriendo.to_f

        # find if the user is allowed to enter to the gym
        allowedGym = Entrada.where(usuarios_id: nil).where(establecimientos_id: establecimiento,:paquete=>usuario.paquete).count
        
        if deuda > 0

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/views/entradas/_form.html.erb
<%= form_for(@entrada) do |f| %>
  <% if @entrada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entrada.errors.count, "error") %> prohibited this entrada from being saved:</h2>

      <ul>
      <% @entrada.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :establecimientos_id %><br />
    <%= f.number_field :establecimientos_id %>
  </div>
  <div class="field">
    <%= f.label :usuarios_id %><br />
    <%= f.number_field :usuarios_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entradas/biometriclogin.html.erb
<div class="page-container">
  <!-- BEGIN PAGE HEAD -->
  <div class="page-head">
    <div class="card" style="left:40%; margin-top: 15%;width:350px">
        <div style="display: flex; flex-wrap: wrap; align-items: center; justify-content: center; padding: 60px 0;">
            <div class="card__circle">
                <!-- div class="folder">
                    
                    <div class="folder__page3"></div>
                    <div class="folder__page2"></div>
                    <div class="folder__page1"></div>
                    
                </div -->
                <img src="/assets/img/fingerprint.png" style="width:135px";/>
                </div>
                <div class="card-information">
                    <div class="card-information__title">Lector dactilar</div>
                    <div class="card-information__text">Usa tu huella digital para ingresar</div>
                    <button class="btn btn-icon btn-2 btn-primary" type="button" id="turnoff-btn" style="display:none">
                    <span class="btn-inner--icon"><i class="far fa-circle"></i></span>
                    
                  </button>
                  <button type="button" class="btn btn-primary btn-sm" id="connectBtn" style="display:none;">Vincular lector</button>
                  <button class="btn btn-icon btn-2 btn-primary" type="button" id="turnon-btn" style="display:none">

                    <span class="btn-inner--icon"><i class="fas fa-circle"></i></span>
                    
                  </button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
var port;
(function() {
  'use strict';

  

  
  let textEncoder = new TextEncoder();
  document.addEventListener('DOMContentLoaded', event => {
    let connectButton = document.querySelector('#connectBtn');

    

    function connect() {
      port.connect().then(() => {
        console.log(port);
        port.onReceive = data => {
          $("#connectBtn").hide();
          let textDecoder = new TextDecoder();
          console.log(textDecoder.decode(data));
          var cardDetails=textDecoder.decode(data).replace(/'/gi, '"');
          if(cardDetails!=""){
            signInByCard(JSON.parse(cardDetails));
          }
          
        }
        port.onReceiveError = error => {
          console.log('Receive error: ' + error)
          $("#connectBtn").show();
        };
      }, error => {
        console.log('Connection error: ' + error)
        $("#connectBtn").show();
      });
    };
    document.getElementById('turnon-btn').addEventListener('click', function() {
        if (port !== undefined) {
            port.send(textEncoder.encode("H")).catch(error => {
            console.log('Send error: ' + error);
            });
        }
        var cardDetails='{"deviceId":"3211"}';
        signInByCard(JSON.parse(cardDetails).deviceId);
    });
    document.getElementById('turnoff-btn').addEventListener('click', function() {
        if (port !== undefined) {
            port.send(textEncoder.encode("L")).catch(error => {
            console.log('Send error: ' + error);
            });
        }
    });
    connectButton.addEventListener('click', function() {
      if (port) {
        port.disconnect();
        connectButton.textContent = 'Vincular lector';
        port = null;
      } else {
        serial.requestPort().then(selectedPort => {
          port = selectedPort;
          connect();
          $("#connectBtn").hide();
        }).catch(error => {
          console.log('Connection error: ' + error);
        });
      }
    });

    serial.getPorts().then(ports => {
      if (ports.length == 0) {
        console.log('No devices found.');
        $("#connectBtn").show();
      } else {
        port = ports[0];
        connect();
      }
    });
  });
})();
function signInByCard(sosn){
  $.post( "/entradas/logWithCard", { device:sosn,authenticity_token:'<%= form_authenticity_token.to_s %>' }, function(result){
    console.log(result);
  }).done(function( data ) {
      console.log(data);
  });
}
</script>

app/views/entradas/edit.html.erb
<h1>Editing entrada</h1>

<%= render 'form' %>

<%= link_to 'Show', @entrada %> |
<%= link_to 'Back', entradas_path %>

app/views/entradas/new.html.erb
<h1>New entrada</h1>

<%= render 'form' %>

<%= link_to 'Back', entradas_path %>

app/views/entradas/nfclogin.html.erb
<div class="page-container">
  <!-- BEGIN PAGE HEAD -->
  <div class="page-head">
    <div class="card" style="left:40%; margin-top: 15%;width:350px">
        <div style="display: flex; flex-wrap: wrap; align-items: center; justify-content: center; padding: 60px 0;">
            <div class="card__circle">
                <!-- div class="folder">
                    
                    <div class="folder__page3"></div>
                    <div class="folder__page2"></div>
                    <div class="folder__page1"></div>
                    
                </div -->
                <img src="/assets/img/contactless-icon.png"/>
                </div>
                <div class="card-information">
                    <div class="card-information__title">Escanea tu membresía</div>
                    <div class="card-information__text">Usa tu membresia para ingresar</div>
                    <button class="btn btn-icon btn-2 btn-primary" type="button" id="turnoff-btn" style="display:none">
                    <span class="btn-inner--icon"><i class="far fa-circle"></i></span>
                    
                  </button>
                  <button type="button" class="btn btn-primary btn-sm" id="connectBtn" style="display:none;">Vincular lector</button>
                  <button class="btn btn-icon btn-2 btn-primary" type="button" id="turnon-btn" style="display:none">

                    <span class="btn-inner--icon"><i class="fas fa-circle"></i></span>
                    
                  </button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
var port;
(function() {
  'use strict';
  let textEncoder = new TextEncoder();
  document.addEventListener('DOMContentLoaded', event => {
    let connectButton = document.querySelector('#connectBtn');
    function connect() {
      port.connect().then(() => {
        console.log(port);
        port.onReceive = data => {
          $("#connectBtn").hide();
          let textDecoder = new TextDecoder();
          console.log(textDecoder.decode(data));
          var cardDetails=textDecoder.decode(data).replace(/'/gi, '"');
          if(cardDetails!=""){
            signInByCard(JSON.parse(cardDetails));
          }
          
        }
        port.onReceiveError = error => {
          console.log('Receive error: ' + error)
          $("#connectBtn").show();
        };
      }, error => {
        console.log('Connection error: ' + error)
        $("#connectBtn").show();
      });
    };
    document.getElementById('turnon-btn').addEventListener('click', function() {
        if (port !== undefined) {
            port.send(textEncoder.encode("H")).catch(error => {
            console.log('Send error: ' + error);
            });
        }
        var cardDetails='{"deviceId":"3211"}';
        signInByCard(JSON.parse(cardDetails).deviceId);
    });
    document.getElementById('turnoff-btn').addEventListener('click', function() {
        if (port !== undefined) {
            port.send(textEncoder.encode("L")).catch(error => {
            console.log('Send error: ' + error);
            });
        }
    });
    connectButton.addEventListener('click', function() {
      if (port) {
        port.disconnect();
        connectButton.textContent = 'Vincular lector';
        port = null;
      } else {
        serial.requestPort().then(selectedPort => {
          port = selectedPort;
          connect();
          $("#connectBtn").hide();
        }).catch(error => {
          console.log('Connection error: ' + error);
        });
      }
    });

    serial.getPorts().then(ports => {
      if (ports.length == 0) {
        console.log('No devices found.');
        $("#connectBtn").show();
      } else {
        port = ports[0];
        connect();
      }
    });
  });
})();
function signInByCard(sosn){
  $.post( "/entradas/logWithCard", { device:sosn,authenticity_token:'<%= form_authenticity_token.to_s %>' }, function(result){
    console.log(result);
  }).done(function( data ) {
      console.log(data);
  });
}
</script>

app/views/entradas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @entrada.id %>
</p>

<p>
  <b>Establecimientos:</b>
  <%= @entrada.establecimientos_id %>
</p>

<p>
  <b>Usuarios:</b>
  <%= @entrada.usuarios_id %>
</p>


<%= link_to 'Edit', edit_entrada_path(@entrada) %> |
<%= link_to 'Back', entradas_path %>