config/routes.rb
Rails.application.routes.draw do
  resources :devices

  # Redirects with constraints
  # Commented out in original; updated syntax for Rails 7
  # get "*path", to: redirect("https://www.sportfit.app/%{path}"), constraints: { protocol: "http://" }
  # get "*path", to: redirect("https://www.sportfit.app/%{path}"), constraints: { subdomain: "" }

  # Trackers
  match "/trackers/weightStats", to: "trackers#weightStats", via: [:get, :post] # Keeping match for multiple verbs
  resources :trackers

  # Eventos
  match "/events/getAll", to: "eventos#getActiveEvents", via: [:get, :post]
  resources :eventos

  resources :mcards
  resources :likes

  # Comentarios
  match "/comments/getAll", to: "comentarios#getAll", via: [:get, :post]
  resources :comentarios do # Evita generar rutas automáticas innecesarias
    member do
      delete :destroy # Ruta DELETE estándar
      post :destroy   # Permitir POST para simular DELETE
    end
  end

  # Nutritions
  match "/nutrition/appointments", to: "nutritions#getMyAppointments", via: [:get, :post]
  resources :nutritions

  resources :entrenamientos

  # Asistencia
  match "/asistencia/stats", to: "asistencia#estadistica", via: [:get, :post]
  match "/asistencia/lista", to: "asistencia#listaDeAsistencia", via: [:get, :post]
  match "/asistencia/startWod", to: "asistencia#startWod", via: [:get, :post]
  match "/asistencia/endWod", to: "asistencia#endWod", via: [:get, :post]
  match "/asistencia/activeWods", to: "asistencia#activeWod", via: [:get, :post]
  get '/asistencia/stats/montly', to: 'asistencia#monthly_chart'
  resources :asistencia

  resources :accesses
  resources :diccionarios
  resources :wod_schedules
  resources :wod_items

  # Wod_roots
  get "/wod_roots/mywods", to: "wod_roots#getMyWods"
  post "/wod_roots/getSingleWodItem", to: "wod_roots#getSingleWodItem"
  post "/wod_roots/getWodItems", to: "wod_roots#getWodItems"
  resources :wod_roots

  resources :ejercicios
  resources :box_schedules
  resources :tickets
  resources :corte_cajas

  # Dashboards
  get "/dashboards/salesInfo", to: "dashboards#salesInfo"
  get "/dashboards/salesInfo2", to: "dashboards#salesInfo2"
  get "/dashboards/salesInfo3", to: "dashboards#salesInfo3"
  post "/", to: "dashboards#dummy"
  resources :dashboards

  resources :paquetes
  resources :correos

  match "/contactme", to: "correos#contactus", via: [:get, :post]

  resources :notificaciones

  # Recompensa_obtenidas
  match "/rewards/myRewards", to: "recompensa_obtenidas#getMyRewards", via: [:get, :post]
  resources :recompensa_obtenidas

  resources :rewards
  # Entradas
  get "/entradas/salir", to: "entradas#logOut"
  post "/entradas/logWithCard", to: "entradas#logWithCard"
  get "/entradas/keypad/:uid", to: "entradas#showKeypad"
  get "/entradas/contactless/:uid", to: "entradas#showNFC"
  get "/entradas/biometric/:uid", to: "entradas#showBiometric"
  post "/entradas/logWithUser", to: "entradas#logWithUser" # Assuming GET; adjust if POST is intended
  match "/entradas/logWithKeyPad", to: "entradas#logWithKeypad", via: [:post, :options]
  resources :entradas

  resources :establecimientos
  resources :pagos
  resources :tipo_cuenta

  # Usuarios
  match "/coinLogin", to: "usuarios#coinlessLogin", via: [:get, :post]
  match "/coinRegister", to: "usuarios#coinlessRegister", via: [:get, :post]
  match "/setPrice", to: "usuarios#coinlessPrice", via: [:get, :post]
  match "/getPrice", to: "usuarios#getCoinlessPrice", via: [:get, :post]
  get "/usuarios/fakeUser", to: "usuarios#fakeUser"
  get "/usuarios/welcomeUser", to: "usuarios#welcomeUser"
  get "/usuarios/openDoor", to: "usuarios#openDoor"
  get "/usuarios/closeDoor", to: "usuarios#closeDoor"
  get "/usuarios/createToken", to: "usuarios#createToken"
  match "/usuarios/fromMobile", to: "usuarios#createMobile", via: [:post, :options]
  match "/usuarios/loginMobile", to: "usuarios#loginMobile", via: [:post, :options]
  match "/usuarios/downloadBeacons", to: "usuarios#downloadBeacons", via: [:post, :options]
  get "/usuarios/downloadPlacesFromNetwork", to: "usuarios#downloadPlacesFromNetwork"
  match "/usuarios/mostActive", to: "usuarios#mostActiveUsers", via: [:post, :get]
  get "/usuarios/stats", to: "usuarios#statsByUser"
  resources :usuarios do
    # Add this line inside the resources block if mylogin is a member action (specific to a user)
    # get 'mylogin', on: :member
    # Or as a collection action (not tied to a specific user)
    get 'login', on: :collection
  end

  post "/usuarios/buscar", to: "usuarios#buscarNombre"

  # Pagos (merged duplicate routes)
  get "/pagos/makePayment", to: "pagos#makePayment" # Original match
  post "/pagos/makePayment", to: "pagos#makePayment" # Explicit POST route
  post "/pagos/corteCaja", to: "pagos#corteCaja"
  get "/pagos/makeCardPayment", to: "pagos#makeCardPayment"
  get "/pagos/pauseUser", to: "pagos#pauseUser"
  get "/pagos/incomingFromGateway", to: "pagos#incomingFromGateway"

  # Removed legacy wildcard route comment
end

app/controllers/asistencia_controller.rb
class AsistenciaController < ApplicationController
  before_action :require_login
  # GET /asistencia
  # GET /asistencia.json
  def index
    if session[:cuser].tipo>3
      redirect_to "/"
      return
    end
    @asistencia = Asistencium.all
    if session[:cuser].tipo>1
      @asistencia=Asistencium.where(:networkid=>session[:networkid])
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @asistencia }
    end
  end

  def apiController
    
  end

  # GET /asistencia/1
  # GET /asistencia/1.json
  def show
    @asistencium = Asistencium.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @asistencium }
    end
  end

  # GET /asistencia/new
  # GET /asistencia/new.json
  def new
    @asistencium = Asistencium.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @asistencium }
    end
  end

  # GET /asistencia/1/edit
  def edit
    @asistencium = Asistencium.find(params[:id])
  end

  def startWod
    response=[]
    horaCero=Time.now.change({min: 0,sec:0 })-15.minutes
    usuarios=Asistencium.where("created_at >= ?",horaCero).where(:user_id=>params[:iniciarwod]).where(:networkid=>session[:cuser].networkid,:transition=>"enter")

    usuarios.each do |singleEntry|
      singleEntry.startwod=Time.now
      singleEntry.save
    end
    respond_to do |format|
      format.json { render json: response.to_json }
    end
  end

  def endWod
    response=Hash.new
    horaCero=Date.today
    usuarios=Asistencium.where("created_at >= ?",horaCero).where(:user_id=>params[:wodstop]).where(:networkid=>session[:cuser].networkid,:transition=>"enter")
    puts usuarios.inspect
    usuarios.each do |singleEntry|
      if singleEntry.endwod==nil && singleEntry.startwod != nil
        singleEntry.endwod=Time.now
        response["minutos"]=TimeDifference.between(singleEntry.startwod, singleEntry.endwod).in_minutes
        singleEntry.save  
      end
    end

    respond_to do |format|
      format.json { render json: response.to_json }
    end
  end

  def activeWod
    response=Hash.new

    existencia=Asistencium.where(:user_id=>session[:cuser].id).where(:transition=>"enter").where("startwod is not null and endwod is null")
    if existencia.length>0
      response["activo"]=true
    else
      response["activo"]=false
    end

    respond_to do |format|
      format.json { render json: response.to_json }
    end
    
  end

  def listaDeAsistencia
    # traemos la lista de hoy
    horaCero=Time.now.change({min: 0,sec:0 })-15.minutes
    puts "horaCero:"+horaCero.to_s+" ------> "+Time.now.to_s
    asistio=[]
    asistencias=Asistencium.where("created_at >= ?",horaCero).where(:networkid=>session[:cuser].networkid,:transition=>"enter")
    response=[]

    asistencias.each do |singleAsistencia|
      nombre=Usuario.find_by_id(singleAsistencia.user_id)
      if nombre==nil
        nombre=Usuario.new
      end
      if asistio.index(singleAsistencia.user_id)==nil
        usuario=Hash.new
        usuario["nombre"]=nombre.nombre+" "+nombre.apellido
        usuario["pago"]=singleAsistencia.activo
        usuario["avatar"]=nombre.foto
        usuario["id"]=nombre.id
        usuario["entrada"]=singleAsistencia.created_at.strftime(" %I:%M%p")
        response.push(usuario)
        asistio.push(singleAsistencia.user_id)
      end
    end

    respond_to do |format|
      format.json { render json: response.to_json }
    end
  end

  def monthly_chart
    # Get the current date (March 02, 2025, based on your setup)
    current_date = Date.today
    # Calculate the start date (6 months ago)
    start_date = current_date - 5.months

    # Build an array of the last 6 months (e.g., Sep 2024 to Feb 2025)
    months = (0..5).map { |i| (current_date - i.months).strftime('%b %Y') }.reverse

    # Fetch Asistencia records based on session[:cuser]
    if session[:cuser][:tipo] == 1
      # Tipo 1 sees all records
      records = Entrada.where(created_at: start_date.beginning_of_month..current_date.end_of_month)
    else
      # Non-tipo 1 sees only their networkid
      records = Entrada.where(
        networkid: session[:cuser][:networkid],
        created_at: start_date.beginning_of_month..current_date.end_of_month
      )
    end

    # Group records by month and count them
    counts_by_month = records.group_by { |r| r.created_at.strftime('%b %Y') }
                             .transform_values(&:count)
                             .tap { |h| months.each { |m| h[m] ||= 0 } } # Ensure all months are included, even with 0

    # Format data for Chart.js
    chart_data = {
      labels: months, # e.g., ["Sep 2024", "Oct 2024", ..., "Feb 2025"]
      datasets: [{
        label: 'Asistencias',
        data: months.map { |month| counts_by_month[month] } # e.g., [5, 10, 8, 12, 7, 9]
      }]
    }

    render json: chart_data
  end


  # Example authentication check (adjust to your setup)
  def require_login
    redirect_to "/" unless session[:cuser].present?
  end

  def estadistica
    workWeek=[Date.today.monday,Date.today.monday+1,Date.today.monday+2,Date.today.monday+3,Date.today.monday+4,Date.today.monday+5]
    # puts "------today"
    # puts Date.today.monday
    # puts "------today"
    finalStats=[]
    cIndex=0
    workWeek.each do |singleDay|
      minutos=0
      puts session[:cuser].id
      asistencias=Asistencium.where('created_at>=?',singleDay).where(:user_id=>session[:cuser].id).where('created_at<=?',singleDay+1.day)
      puts asistencias.inspect
      elementos=asistencias.index_by(&:transition).keys.uniq
      if elementos.length==1 and elementos.join("").index("enter")!=nil
        futuro=asistencias.first.arrival_time+3.hours
        if Time.now>futuro
          # hay que insertar un elemento de fin en 1 hora
          finTiempo=Asistencium.new
          finTiempo.user_id=session[:cuser].id
          finTiempo.establecimiento_id=asistencias.first.establecimiento_id
          finTiempo.networkid=asistencias.first.networkid
          finTiempo.activo=asistencias.first.activo
          finTiempo.arrival_time=asistencias.first.arrival_time+1.hour
          finTiempo.minutos=60
          finTiempo.transition="exit"
          finTiempo.save
          minutos=60
        else
          minutos=TimeDifference.between(asistencias.first.arrival_time, Time.now).in_minutes
        end
      end
      if elementos.length==1 and elementos.join("").index("exit")!=nil
          # hay que insertar un elemento de principio en 1 hora anterior
          finTiempo=Asistencium.new
          finTiempo.user_id=session[:cuser].id
          finTiempo.establecimiento_id=asistencias.last.establecimiento_id
          finTiempo.networkid=asistencias.last.networkid
          finTiempo.activo=asistencias.last.activo
          finTiempo.arrival_time=asistencias.last.arrival_time-1.hour
          finTiempo.transition="enter"
          finTiempo.save
          minutos=60
      end
      if minutos==0
        waitFor='enter'
        fechaInicio=nil
        asistencias=Asistencium.where('created_at>=?',singleDay).where(:user_id=>session[:cuser].id).where('created_at<=?',singleDay+1.day)
        asistencias.each do |singleAsistencia|
          # debemos empezar con una entrada
          if singleAsistencia.transition==waitFor
            if fechaInicio!=nil
              minutos=minutos+TimeDifference.between(fechaInicio, singleAsistencia.arrival_time).in_minutes
            else
              fechaInicio=singleAsistencia.arrival_time
            end

            if waitFor=="enter"
              waitFor="exit"
            else
              waitFor="enter"
              fechaInicio=nil
            end
          end
        end
        finalStats.push(minutos)
      end
      puts "------asistencia"
      puts asistencias.inspect
      # caso 1, solo hay 1 enter

      # caso 2, hay varios enter

      # caso 3 hay 1 exit

      # caso 4, hay varios exit

      # caso 5, varios enter seguidos y varios exit seguidos

      # caso 6, hay 
    end

    respond_to do |format|
      format.json { render json: finalStats.to_json}
    end

  end

  # POST /asistencia
  # POST /asistencia.json
  def asistencium_params
    params.require(:asistencium).permit(:beacon, :major,:minor,:transition)
  end

  def create
    
    @asistencium = Asistencium.new
    @asistencium.transition=params[:transition]
    @asistencium.user_id=session[:cuser].id
    if @asistencium.transition=="exit"
      # buscamos el ultimo enter para calcular el tiempo total
      lastEnter=Asistencium.where(:transition=>"enter",:user_id=>session[:cuser].id).last
      minutos=TimeDifference.between(lastEnter.created_at, Time.now).in_minutes
      @asistencium.minutos=minutos
    end
    # buscamos el beacon a quien le pertenece
    establecimiento=Establecimiento.where(:beacon=>params[:beacon],:major=>params[:major],:minor=>params[:minor]).last
    if @asistencium.arrival_time == nil or @asistencium.arrival_time == ''
      @asistencium.arrival_time=Time.now
      @asistencium.save
    end
    if establecimiento==nil
      @asistencium.activo=0
    else 
      @asistencium.establecimiento_id=establecimiento.id
      @asistencium.networkid=session[:cuser].networkid
      @asistencium.arrival_time=Time.now
      @asistencium.save
      # revisar si esta permitido estar aqui
      paquete=Entrada.where(:establecimientos_id=>establecimiento.id).last
      rewardExecuted = 0
      if paquete!=nil
        if paquete.paquete==session[:cuser].paquete && paquete.paquete != nil
          # aqui por ultimo verificamos que exista un pago
          pagoActivo=Pago.where(:usuarios_id=>session[:cuser].id).where('vence>=?',Time.now)
          if pagoActivo.length>0 or (session[:cuser].finalfecha>=DateTime.now and session[:cuser].finalfecha!=nil)
            @asistencium.activo=1  
            rewardService(session[:cuser],establecimiento.id, 1)
          else

app/helpers/asistencia_helper.rb
module AsistenciaHelper
end

app/views/asistencia/_form.html.erb
<%= form_for(@asistencium) do |f| %>
  <% if @asistencium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asistencium.errors.count, "error") %> prohibited this asistencium from being saved:</h2>

      <ul>
      <% @asistencium.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :arrival_time %><br />
    <%= f.datetime_select :arrival_time %>
  </div>
  <div class="field">
    <%= f.label :leaving_time %><br />
    <%= f.datetime_select :leaving_time %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :establecimiento_id %><br />
    <%= f.number_field :establecimiento_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/asistencia/edit.html.erb
<h1>Editing asistencium</h1>

<%= render 'form' %>

<%= link_to 'Show', @asistencium %> |
<%= link_to 'Back', asistencia_path %>

app/views/asistencia/index.html.erb
<div class="card shadow">
  <div class="card-header border-0">
      <div class="row align-items-center">
        <div class="col">
          <h3 class="mb-0">Tabla de asistencia</h3>
        </div>
        <div class="col text-right">
          <% if session[:cuser].tipo==1 %>
            <% link_to 'New Asistencium', new_asistencium_path, :class=>'btn btn-sm btn-primary' %>
          <% end %>
        </div>
      </div>
  </div>
  <div class="table-responsive">
    <table class="table align-items-center table-flush">
      <thead class="thead-light">
        <tr>
          <th>Hora de llegada</th>
          <th>Hora de partida</th>
          <th>Usuario</th>
          <th>Establecimiento</th>
          <th></th>
        </tr>
      </thead>
      <tbody>

        <% @asistencia.each do |asistencium| %>
          <tr>
            <td><%= asistencium.arrival_time %></td>
            <td><%= asistencium.leaving_time %></td>
            <% 
            persona=Usuario.where(:id=>asistencium.user_id).last
            if persona!=nil %>
              <td><%= persona.nombre %> <%= persona.apellido %></td>  
            <% else %>
              <td>Usuario no encontrado</td>  
            <% end %>
            
            <% establecimiento=Establecimiento.find_by_id(asistencium.establecimiento_id)
            if establecimiento!=nil %>
            <td><%= establecimiento.nombre %></td>  
            <% else %>
            <td>Establecimiento no encontrado</td>
            <% end %>
            <% if session[:cuser].tipo==1 %>
            <td>
              <div class="dropdown">
                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-ellipsis-v"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                    <%= link_to 'Show', asistencium, :class=>"dropdown-item" %>
                    <%= link_to 'Edit', edit_asistencium_path(asistencium), :class=>"dropdown-item" %>
                    <%= link_to 'Destroy', asistencium, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"dropdown-item" %>
                </div>
              </div>
            </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br />
  </div>
</div>

app/views/asistencia/new.html.erb
<h1>New asistencium</h1>

<%= render 'form' %>

<%= link_to 'Back', asistencia_path %>

app/views/asistencia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Arrival time:</b>
  <%= @asistencium.arrival_time %>
</p>

<p>
  <b>Leaving time:</b>
  <%= @asistencium.leaving_time %>
</p>

<p>
  <b>User:</b>
  <%= @asistencium.user_id %>
</p>

<p>
  <b>Establecimiento:</b>
  <%= @asistencium.establecimiento_id %>
</p>


<%= link_to 'Edit', edit_asistencium_path(@asistencium) %> |
<%= link_to 'Back', asistencia_path %>